### ISSUE TITLE
openpathsampling errors

### ISSUE THREAD

**Issue by jchodera** [choderalab/ligand-binding-pathsampling#1]
@jhprinz : I've created a very basic attempt at ligand unbinding for a simple CB7:B2 host-guest system (using `openmmtools >=0.8.0`):
https://github.com/choderalab/ligand-binding-pathsampling/tree/master/host-guest/cb7-b2

The current script dies with the error

```
[LSKI1497:ligand-binding-pathsampling/host-guest/cb7-b2] choderaj% python -i run-ops.py
Creating host-guest system...
Creating template...
Creating an integrator...
Selecting a platform...
Creating engine...
Creating a "hot" engine...
Initializing storage...
(store.engines[DynamicsEngine], 11, UUID('137432cf-5ab5-11e6-9087-000000000010'))
(store.engines[DynamicsEngine], 11, UUID('137432cf-5ab5-11e6-9087-000000000014'))
CPU
CPU
<openpathsampling.engines.openmm.topology.MDTrajTopology object at 0x119cf75d0>
Traceback (most recent call last):
  File "run-ops.py", line 111, in <module>
    storage.save([compute_contacts])
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.py", line 617, in save
    return [self.save(part, idx) for part in obj]
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.py", line 628, in save
    return store, store_idx, store.save(obj, idx)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 1371, in save
    reference = super(UniqueNamedObjectStore, self).save(obj, idx)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 1183, in save
    reference = super(NamedObjectStore, self).save(obj)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 853, in save
    self._save(obj, n_idx)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/storage/stores/collectivevariable.py", line 18, in _save
    self.add_diskcache(cv)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/storage/stores/collectivevariable.py", line 96, in add_diskcache
    chunksize=chunksize
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/storage/stores/snapshot.py", line 939, in add_cv
    params = NetCDFPlus.get_value_parameters(cv(template))
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/chaindict.py", line 231, in __getitem__
    return self._post[items]
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/chaindict.py", line 244, in __getitem__
    return np.array(self._post[items])
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/chaindict.py", line 277, in __getitem__
    return self._post[[items]][0]
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/chaindict.py", line 72, in __getitem__
    rep = self._post[nones]
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/chaindict.py", line 65, in __getitem__
    results = self._get_list(items)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/chaindict.py", line 360, in _get_list
    if self.scalarize_numpy_singletons and results.shape[-1] == 1:
AttributeError: 'tuple' object has no attribute 'shape'
```

Any ideas?

**Comment by jchodera** [comment]
Tagging @dwhswenson since this will be of use to him as well.

**Comment by jchodera** [comment]
Note that the state and interface definitions are currently suboptimal. MDTraj doesn't have a "compute the distance between the centers of mass of two residues" function, so I had to use `compute_contacts`, and may not be using your CV definition scheme correctly. I currently have:

``` python
# Define order parameters
# Compute the closest heavy atom distances between receptor and ligand
# TODO: How do we restrict this to only residues 0 and 1?
print(template.topology)
compute_contacts = paths.MDTrajFunctionCV(
    name="compute_contacts",
    contacts=[[0,1]],
    f=md.compute_contacts,
    topology=template.topology,
    scheme='closest-heavy',
    ignore_nonprotein=False,
    periodic=True
).with_diskcache()
storage.save([compute_contacts])

# Create CV states for bound and unbound
def compute_cv(snapshot, center, compute_contacts):
    [distances, residue_pairs] = compute_contacts(snapshot)
    return distances[0]
```

**Comment by jhprinz** [comment]
> and may not be using your CV definition scheme correctly

No, that was all correct. 

But, `MDTrajFunctionCV` will assume that the output is a numpy array by default (my fault, I thought that is always the case) and there is an default option called `cv_scalarize_numpy_singletons=True` which will remove the last axis if it has size 1. This is e.g. if you run a function that can output several angles but you use it for one to get an
array of shape `(N, )` instead of size `(N, 1)` as you would expect. Just turn this off by setting 

``` py
compute_contacts = paths.MDTrajFunctionCV(
    name="compute_contacts",
    contacts=[[0,1]],
    f=md.compute_contacts,
    topology=template.topology,
    scheme='closest-heavy',
    ignore_nonprotein=False,
    periodic=True,
    cv_scalarize_numpy_singletons=False
).with_diskcache()
```

We might set the default to `False` if there are functions that do not output numpy arrays.

Let me know if it does not work...

**Comment by jchodera** [comment]
Thanks! Fixed. Now I get this error:

```
[LSKI1497:ligand-binding-pathsampling/host-guest/cb7-b2] choderaj% python run-ops.py 
Creating host-guest system...
Creating template...
Creating an integrator...
Selecting a platform...
Creating engine...
Creating a "hot" engine...
Initializing storage...
(store.engines[DynamicsEngine], 11, UUID('dccd9a6e-5afa-11e6-971a-000000000010'))
(store.engines[DynamicsEngine], 11, UUID('dccd9a6e-5afa-11e6-971a-000000000014'))
CPU
CPU
<openpathsampling.engines.openmm.topology.MDTrajTopology object at 0x11a5f7490>
Traceback (most recent call last):
  File "run-ops.py", line 148, in <module>
    interface_list[state][idx] = paths.CVRangeVolume(cv_state[state], lambda_max=level)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/volume.py", line 252, in __init__
    self.lambda_max = float(lambda_max)
TypeError: __float__ returned non-float (type Quantity)
```

Am I guessing correctly that we have to strip units from any CVs in order for them to work with OpenPathSampling?

**Comment by jchodera** [comment]
I'm stripping the units, and now get this error:

```
[LSKI1497:ligand-binding-pathsampling/host-guest/cb7-b2] choderaj% git push
Counting objects: 9, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 663 bytes | 0 bytes/s, done.
Total 5 (delta 1), reused 0 (delta 0)
To git@github.com:choderalab/ligand-binding-pathsampling.git
   b900d86..f90294a  master -> master
[LSKI1497:ligand-binding-pathsampling/host-guest/cb7-b2] choderaj% python run-ops.py
Creating host-guest system...
Creating template...
Creating an integrator...
Selecting a platform...
Creating engine...
Creating a "hot" engine...
Initializing storage...
(store.engines[DynamicsEngine], 11, UUID('2c31978f-5afb-11e6-b650-000000000010'))
(store.engines[DynamicsEngine], 11, UUID('2c31978f-5afb-11e6-b650-000000000014'))
CPU
CPU
<openpathsampling.engines.openmm.topology.MDTrajTopology object at 0x11a4e9450>
Traceback (most recent call last):
  File "run-ops.py", line 154, in <module>
    storage.save(stAll)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.py", line 628, in save
    return store, store_idx, store.save(obj, idx)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 1183, in save
    reference = super(NamedObjectStore, self).save(obj)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 853, in save
    self._save(obj, n_idx)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 443, in _save
    self.vars['json'][idx] = obj
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.py", line 104, in __setitem__
    self.variable[key] = self.setter(value)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.py", line 911, in <lambda>
    setter = lambda v: self.simplifier.to_json_object(v)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 433, in to_json_object
    simplified = self.simplify_object(obj)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 66, in simplify_object
    '_dict': self.simplify(obj.to_dict(), obj.base_cls_name)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 530, in simplify
    return super(UUIDObjectJSON, self).simplify(obj, base_type)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 138, in simplify
    key: self.simplify(o) for key, o in obj.iteritems()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 139, in <dictcomp>
    if key not in self.excluded_keys
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 525, in simplify
    store.save(obj)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 1183, in save
    reference = super(NamedObjectStore, self).save(obj)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 853, in save
    self._save(obj, n_idx)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 443, in _save
    self.vars['json'][idx] = obj
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.py", line 104, in __setitem__
    self.variable[key] = self.setter(value)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.py", line 911, in <lambda>
    setter = lambda v: self.simplifier.to_json_object(v)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 433, in to_json_object
    simplified = self.simplify_object(obj)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 66, in simplify_object
    '_dict': self.simplify(obj.to_dict(), obj.base_cls_name)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 530, in simplify
    return super(UUIDObjectJSON, self).simplify(obj, base_type)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 138, in simplify
    key: self.simplify(o) for key, o in obj.iteritems()
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 139, in <dictcomp>
    if key not in self.excluded_keys
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 525, in simplify
    store.save(obj)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 1371, in save
    reference = super(UniqueNamedObjectStore, self).save(obj, idx)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 1183, in save
    reference = super(NamedObjectStore, self).save(obj)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/objects.py", line 853, in save
    self._save(obj, n_idx)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/storage/stores/collectivevariable.py", line 15, in _save
    self.vars['json'][idx] = cv
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.py", line 104, in __setitem__
    self.variable[key] = self.setter(value)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/netcdfplus.py", line 911, in <lambda>
    setter = lambda v: self.simplifier.to_json_object(v)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 433, in to_json_object
    simplified = self.simplify_object(obj)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 66, in simplify_object
    '_dict': self.simplify(obj.to_dict(), obj.base_cls_name)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/collectivevariable.py", line 325, in to_dict
    dct[callable_argument] = ObjectJSON.callable_to_dict(self.cv_callable)
  File "/Users/choderaj/miniconda/lib/python2.7/site-packages/openpathsampling-0.9.0-py2.7.egg/openpathsampling/netcdfplus/dictify.py", line 346, in callable_to_dict
    word_wrap(err, 60))
RuntimeError: Cannot store function! 

The function you try to save relies on globally set
variables and these cannot be saved since storage has no
access to the global scope which includes imports!

We require that the following globals: ['unit'] either

1. be replaced by constants
2. be defined inside your function,

        unit= ...

3. imports need to be "re"-imported inside your function

        import unit

4. be passed as an external parameter (not for imports!)

        my_cv = FunctionCV("cv_name", compute_cv,
                    unit=unit)

    and change your function definition like this

        def compute_cv(snapshot, ...,
                unit):
```

**Comment by jchodera** [comment]
Let me fork this repo and open a PR, since it will be easier to comment line by line then.

**Comment by dwhswenson** [comment]
Add `import simtk.unit as unit` **inside** the function `compute_cv`.

**Comment by dwhswenson** [comment]
(or from `simtk import unit` or however you prefer -- but the CV can't use a package that is imported outside the CV, otherwise it can't be reloaded.)

**Comment by jhprinz** [comment]
Hi John, aren't you in NY? 

Okay, first thing is kind of a bug. You can use Quantities and they are saved but the `CVRangeVolume` (not this will be renamed) cannot deal with units yet. This never happened, but it makes sense. If your cv has unit and you specify a unit it should work. I will add a fix...

The second is reporting that you used a globally defined package / function `unit` in your function definition. Meaning it will look for it in the global scope and a function has no access to this context so it cannot be saved. Or, it can be saved if you guarantee that when loaded you will manually take care that unit is loaded or in short. Do what David said.

**Comment by jhprinz** [comment]
I think we should add unit to the allowed packages (my fault). Can you try if

```
paths.netcdfplus.dictify.ObjectJSON.safe_modules += ['simtk']
```

works

**Comment by jchodera** [comment]
Here's a clean PR:
https://github.com/choderalab/ligand-binding-pathsampling/pull/3

> Add import simtk.unit as unit inside the function compute_cv.

Thanks!
